"""
Storm Baler backend prototype (FastAPI)
========================================

Serves the site-selection scoring model and live unit-monitoring
data over a REST API, backed by a local SQLite file. A background
task simulates buoy sensor drift every 3 seconds and writes each
reading to the database, so the API looks and behaves like a real
live feed even before any hardware is wired up.

To go from prototype to production: replace `simulate_tick()`
with your real buoy ingestion (MQTT subscriber, LoRaWAN webhook,
etc.) that calls the same `UPDATE sites ...` / `INSERT INTO
readings ...` statements. Nothing else in the API needs to change.

Run:
    pip install -r requirements.txt
    uvicorn main:app --reload

Interactive API docs (auto-generated by FastAPI):
    http://127.0.0.1:8000/docs
"""

import asyncio
import random
import sqlite3
from contextlib import asynccontextmanager
from datetime import datetime, timezone
from typing import List

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

DB_PATH = "storm_baler.db"

# ---------------------------------------------------------------
# Scoring model — mirrors the frontend prototype's weights/curve.
# Tune these to match your paper's actual methodology; they are
# reasonable placeholders, not derived from your source material.
# ---------------------------------------------------------------
WEIGHTS = {"flow": 0.30, "debris": 0.30, "flood": 0.25, "solar": 0.15}


def flow_score(v: float) -> float:
    """Rewards flow velocity inside the 0.5-3.0 m/s ideal band."""
    if v < 0.5:
        return (v / 0.5) * 60
    if v <= 3.0:
        return 60 + ((v - 0.5) / 2.5) * 40
    return max(40, min(100, 100 - (v - 3.0) * 15))


def composite_score(flow: float, debris: float, flood: float, solar: float) -> int:
    fs = flow_score(flow)
    total = (
        fs * WEIGHTS["flow"]
        + debris * WEIGHTS["debris"]
        + flood * WEIGHTS["flood"]
        + solar * WEIGHTS["solar"]
    )
    return round(total)


def clamp(v: float, lo: float, hi: float) -> float:
    return max(lo, min(hi, v))


def alert_level(flow: float, flood: float) -> str:
    risk = flow * 20 + flood * 0.5
    if risk > 95:
        return "High"
    if risk > 60:
        return "Moderate"
    return "Low"


# ---------------------------------------------------------------
# Seed data — same five candidate sites as the frontend demo,
# so scores/ranking line up with what you've already shown.
# ---------------------------------------------------------------
SEED_SITES = [
    ("S1", "Marikina River — Tumana Bridge", 1.9, 58, 72, 80),
    ("S2", "Pasig River — Guadalupe", 1.2, 74, 65, 60),
    ("S3", "San Juan River — Ortigas Ave", 0.7, 41, 48, 55),
    ("S4", "Marikina River — Nangka", 2.4, 66, 83, 88),
    ("S5", "Pasig River — Lambingan", 1.5, 52, 59, 70),
]


# ---------------------------------------------------------------
# Database helpers
# ---------------------------------------------------------------
def get_db() -> sqlite3.Connection:
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_db() -> None:
    conn = get_db()
    cur = conn.cursor()
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS sites (
            id TEXT PRIMARY KEY,
            name TEXT NOT NULL,
            flow REAL, debris REAL, flood REAL, solar REAL
        )
        """
    )
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS readings (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            site_id TEXT NOT NULL,
            ts TEXT NOT NULL,
            flow REAL, debris REAL, flood REAL, solar REAL, score INTEGER
        )
        """
    )
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS units (
            id TEXT PRIMARY KEY,
            site_id TEXT NOT NULL,
            deployed_at TEXT NOT NULL,
            plastic_load REAL,
            bales INTEGER,
            active INTEGER DEFAULT 1
        )
        """
    )
    cur.execute("SELECT COUNT(*) AS c FROM sites")
    if cur.fetchone()["c"] == 0:
        cur.executemany(
            "INSERT INTO sites (id, name, flow, debris, flood, solar) VALUES (?,?,?,?,?,?)",
            SEED_SITES,
        )
    conn.commit()
    conn.close()


# ---------------------------------------------------------------
# Response models
# ---------------------------------------------------------------
class Site(BaseModel):
    id: str
    name: str
    flow: float
    debris: float
    flood: float
    solar: float
    score: int


class Unit(BaseModel):
    id: str
    site_id: str
    site_name: str
    deployed_at: str
    flow: float
    flood_alert: str
    plastic_load: float
    bales: int


# ---------------------------------------------------------------
# Background sensor simulation — the only place touching fake
# data. Swap this out for real buoy ingestion when hardware is
# ready; every route below just reads whatever is in the DB.
# ---------------------------------------------------------------
async def simulate_tick() -> None:
    while True:
        await asyncio.sleep(3)
        conn = get_db()
        cur = conn.cursor()

        rows = cur.execute("SELECT * FROM sites").fetchall()
        for r in rows:
            flow = clamp(r["flow"] + random.uniform(-0.09, 0.09), 0.2, 3.6)
            debris = clamp(r["debris"] + random.uniform(-2, 2), 5, 98)
            flood = clamp(r["flood"] + random.uniform(-1, 1), 10, 98)
            solar = clamp(r["solar"] + random.uniform(-1, 1), 20, 99)
            score = composite_score(flow, debris, flood, solar)

            cur.execute(
                "UPDATE sites SET flow=?, debris=?, flood=?, solar=? WHERE id=?",
                (flow, debris, flood, solar, r["id"]),
            )
            cur.execute(
                "INSERT INTO readings (site_id, ts, flow, debris, flood, solar, score) "
                "VALUES (?,?,?,?,?,?,?)",
                (r["id"], datetime.now(timezone.utc).isoformat(), flow, debris, flood, solar, score),
            )

        units = cur.execute("SELECT * FROM units WHERE active=1").fetchall()
        for u in units:
            plastic_load = clamp(u["plastic_load"] + random.uniform(-3, 3), 10, 98)
            bales = u["bales"] + (1 if random.random() < 0.15 else 0)
            cur.execute(
                "UPDATE units SET plastic_load=?, bales=? WHERE id=?",
                (plastic_load, bales, u["id"]),
            )

        conn.commit()
        conn.close()


@asynccontextmanager
async def lifespan(app: FastAPI):
    init_db()
    task = asyncio.create_task(simulate_tick())
    yield
    task.cancel()


app = FastAPI(title="NetZero Wave API", lifespan=lifespan)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # fine for a local prototype; scope this down before deploying
    allow_methods=["*"],
    allow_headers=["*"],
)


def _unit_response(u: sqlite3.Row, site_name: str, flow: float, flood: float) -> Unit:
    return Unit(
        id=u["id"],
        site_id=u["site_id"],
        site_name=site_name,
        deployed_at=u["deployed_at"],
        flow=flow,
        flood_alert=alert_level(flow, flood),
        plastic_load=u["plastic_load"],
        bales=u["bales"],
    )


# ---------------------------------------------------------------
# Routes
# ---------------------------------------------------------------
@app.get("/api/sites", response_model=List[Site])
def list_sites():
    """All candidate sites with their latest reading, ranked by score."""
    conn = get_db()
    rows = conn.execute("SELECT * FROM sites").fetchall()
    conn.close()
    sites = [
        Site(
            id=r["id"],
            name=r["name"],
            flow=r["flow"],
            debris=r["debris"],
            flood=r["flood"],
            solar=r["solar"],
            score=composite_score(r["flow"], r["debris"], r["flood"], r["solar"]),
        )
        for r in rows
    ]
    return sorted(sites, key=lambda s: s.score, reverse=True)


@app.get("/api/sites/{site_id}/history")
def site_history(site_id: str, limit: int = 50):
    """Recent raw readings for one site — handy for charting a trend."""
    conn = get_db()
    rows = conn.execute(
        "SELECT ts, flow, debris, flood, solar, score FROM readings "
        "WHERE site_id=? ORDER BY id DESC LIMIT ?",
        (site_id, limit),
    ).fetchall()
    conn.close()
    if not rows:
        raise HTTPException(404, "No readings yet for this site")
    return list(reversed([dict(r) for r in rows]))


@app.post("/api/deploy/{site_id}", response_model=Unit)
def deploy_site(site_id: str):
    """Deploy a storm baler unit to a candidate site (idempotent if already deployed)."""
    conn = get_db()
    site = conn.execute("SELECT * FROM sites WHERE id=?", (site_id,)).fetchone()
    if not site:
        conn.close()
        raise HTTPException(404, "Unknown site")

    existing = conn.execute(
        "SELECT * FROM units WHERE site_id=? AND active=1", (site_id,)
    ).fetchone()
    if existing:
        conn.close()
        return _unit_response(existing, site["name"], site["flow"], site["flood"])

    count = conn.execute("SELECT COUNT(*) AS c FROM units").fetchone()["c"]
    unit_id = f"PB-{count + 1:02d}"
    conn.execute(
        "INSERT INTO units (id, site_id, deployed_at, plastic_load, bales, active) "
        "VALUES (?,?,?,?,?,1)",
        (unit_id, site_id, datetime.now(timezone.utc).isoformat(), site["debris"], 0),
    )
    conn.commit()
    row = conn.execute("SELECT * FROM units WHERE id=?", (unit_id,)).fetchone()
    conn.close()
    return _unit_response(row, site["name"], site["flow"], site["flood"])


@app.get("/api/units", response_model=List[Unit])
def list_units():
    """All currently deployed units with their latest live metrics."""
    conn = get_db()
    rows = conn.execute("SELECT * FROM units WHERE active=1").fetchall()
    result = []
    for u in rows:
        site = conn.execute("SELECT * FROM sites WHERE id=?", (u["site_id"],)).fetchone()
        result.append(_unit_response(u, site["name"], site["flow"], site["flood"]))
    conn.close()
    return result


@app.get("/api/units/{unit_id}", response_model=Unit)
def get_unit(unit_id: str):
    conn = get_db()
    u = conn.execute(
        "SELECT * FROM units WHERE id=? AND active=1", (unit_id,)
    ).fetchone()
    if not u:
        conn.close()
        raise HTTPException(404, "Unit not found or retired")
    site = conn.execute("SELECT * FROM sites WHERE id=?", (u["site_id"],)).fetchone()
    conn.close()
    return _unit_response(u, site["name"], site["flow"], site["flood"])


@app.delete("/api/units/{unit_id}")
def retire_unit(unit_id: str):
    """Retire a deployed unit (e.g. for redeployment elsewhere)."""
    conn = get_db()
    conn.execute("UPDATE units SET active=0 WHERE id=?", (unit_id,))
    conn.commit()
    conn.close()
    return {"ok": True}